AllCops:
  Exclude:
    - modis.gemspec
    - lib/modis/active_model_dirty_5_1.rb
    - vendor/**/*

LineLength:
  Enabled: false

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Style/StructInheritance:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Security/YAMLLoad:
  Enabled: false
